# =========================
# Network IDS Configuration
# =========================

# IDS capture mode:
#   rspan   → VLAN-based SPAN / RSPAN
#   erspan  → IP/GRE-based ERSPAN
mode: rspan

# Interface connected to:
# - RSPAN VLAN trunk
# - OR ERSPAN routed network
interface: ens19

# Store captured packets in memory (NOT recommended)
store_packets: false


# =========================
# Detection Settings
# =========================

syn_flood:
  threshold: 100        # packets
  window: 10            # seconds

port_scan:
  threshold: 20         # number of unique ports


# =========================
# Logging
# =========================

logging:
  file: logs/alerts.log
  level: INFO
